"""
Configuration constants for the Password Manager.
"""

import os

# Database configuration
DB_NAME = "vault.db"
DB_TABLE_NAME = "vault"
SALT_TABLE_NAME = "master_salt"

# Security configuration
PBKDF2_ITERATIONS = 600000  # High iteration count for key derivation
SALT_LENGTH = 32  # 32 bytes = 256 bits
KEY_LENGTH = 32  # 32 bytes for Fernet key

# Password generation configuration
DEFAULT_PASSWORD_LENGTH = 20
PASSWORD_CHARSET = {
    'lowercase': 'abcdefghijklmnopqrstuvwxyz',
    'uppercase': 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'digits': '0123456789',
    'symbols': '!@#$%^&*()_+-=[]{}|;:,.<>?'
}

# Application configuration
APP_NAME = "Secure Vault Password Manager By Daniyal Shahid"
APP_VERSION = "1.2.0"
GUI_WINDOW_SIZE = "1250x710" # Width x Height
MAX_PASSWORD_LENGTH = 100
MIN_PASSWORD_LENGTH = 8

# Validation patterns
SERVICE_PATTERN = r'^[a-zA-Z0-9\-\.\:\/\ ]*$'  # Allow basic URL characters and spaces
USERNAME_PATTERN = r'^[a-zA-Z0-9_@\.\-]*$'  # Basic username pattern

# PDF Export Configuration
PDF_EXPORT_TITLE = "Password Manager Report"
PDF_AUTHOR = "Secure Vault-  Daniyal Shahid"
PDF_COMPANY = "Secure Vault Password Manager-  Daniyal Shahid"
PDF_FOOTER_TEXT = "Confidential - Generated by Daniyal Shahid - Secure Vault Password Manager"

# Colors for GUI
COLORS = {
    'primary': '#3498db',
    'secondary': '#2c3e50',
    'success': '#27ae60',
    'danger': '#e74c3c',
    'warning': '#f39c12',
    'info': '#17a2b8',
    'light': '#ecf0f1',
    'dark': '#2c3e50',
    'background': '#f8f9fa',
    'text': '#333333',
    'border': '#dee2e6'
}

# PDF Colors
PDF_COLORS = {
    'header': '#2c3e50',
    'odd_row': '#f8f9fa',
    'even_row': '#ffffff',
    'border': '#dee2e6',
    'text': '#333333',
    'accent': '#3498db'
}